### ISSUE TITLE
regr.pkl file not available

### ISSUE THREAD

**Issue by zperfet** [exe1023/DialEvalMetrics#3]
when i run "python usr_fed/usr/usr_server.py", error arrears:
Traceback (most recent call last):
  File "usr_server.py", line 1, in <module>
    import usr
  File "/home/zper/DialEvalMetrics/usr_fed/usr/usr.py", line 6, in <module>
    import regression
  File "/home/zper/DialEvalMetrics/usr_fed/usr/regression.py", line 6, in <module>
    with open('regr.pkl','rb')as f:
FileNotFoundError: [Errno 2] No such file or directory: 'regr.pkl'

after i wget https://github.com/Shikib/usr/blob/master/examples/regr.pkl from original usr model github,
error also appears:
pickle invalid load key, '\x0a'.
i wonder if you can provide your pkl file, thanks.

**Comment by exe1023** [comment]
Hi, I have pushed the pkl file. Sorry for the inconvenience.
